name: elpcjd
channels:
  - defaults
dependencies:
  - python=2.7.14
  - pandas=0.22.0
  - mysql=5.7.20
  - sqlalchemy=1.2.1
  - requests=2.18.4
  - django=1.11.8
  - pip:
    - django-bootstrap4==0.0.5
    - mysql-connector==2.1.6
    - mysql-python==1.2.5
    - mysqlclient==1.3.12