# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-12 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Census',
            fields=[
                ('tract', models.BigIntegerField(primary_key=True, serialize=False)),
                ('geo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'census',
                'managed': False,
                'verbose_name_plural': 'census',
            },
        ),
        migrations.CreateModel(
            name='Neighborhoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood', models.CharField(blank=True, max_length=40, null=True)),
                ('geo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'neighborhoods',
                'managed': False,
                'verbose_name_plural': 'neighborhoods',
            },
        ),
        migrations.CreateModel(
            name='Wards',
            fields=[
                ('ward', models.IntegerField(primary_key=True, serialize=False)),
                ('geo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wards',
                'managed': False,
                'verbose_name_plural': 'wards',
            },
        ),
        migrations.AlterModelOptions(
            name='measurements',
            options={'managed': False, 'verbose_name_plural': 'measurements'},
        ),
        migrations.AlterModelOptions(
            name='notes',
            options={'managed': False, 'verbose_name_plural': 'notes'},
        ),
        migrations.AlterModelOptions(
            name='sessions',
            options={'managed': False, 'verbose_name_plural': 'sessions'},
        ),
        migrations.AlterModelOptions(
            name='streams',
            options={'managed': False, 'verbose_name_plural': 'streams'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False, 'verbose_name_plural': 'users'},
        ),
    ]
