# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-22 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_tracts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hexagons',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('display', models.CharField(blank=True, max_length=40, null=True)),
                ('geo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hexagons',
                'managed': False,
                'verbose_name_plural': 'hexagons',
            },
        ),
        migrations.CreateModel(
            name='Zipcodes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('display', models.CharField(blank=True, max_length=40, null=True)),
                ('geo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'zipcodes',
                'managed': False,
                'verbose_name_plural': 'zipcodes',
            },
        ),
    ]
